export declare function noop(): void;
export declare function isFunction<T extends Function>(value: any): value is T;
export declare function isObject<T>(value: any): value is T;
export declare function isArray<T>(value: any): value is Array<T>;
export declare function isUndefined(value: any): value is undefined;
export declare function isString(value: any): value is string;
export declare function isNumber(value: any): value is number;
export declare const getPrototypeOf: (o: any) => any;
export declare function isPureObject<T>(value: any): value is T;
export declare function warning(expected: boolean, message: string): void;
export declare function assert(expected: boolean, message: string): void | never;
